### ISSUE TITLE
Change the reference for Affymetrix arrays

### ISSUE THREAD

**Issue by jgarces02** [gustaveroussy/EaCoN#17]
Hi (again) @CS-GustaveRoussy, 

I guess the currently approach of `EaCoN` is taking account those references provided by Affymetrix to determine CNVs, am I right? Would be another way to build and use a custom reference, eg. compare normal-tumor CELs? (I know that rawcopy is able to do this with `rawcopy.makeReference`, but it's difficult to understand because it's poorly documented).

Thanks a lot!

**Comment by aoumess** [comment]
Sorry for not answering your question (years) before !
I understand your request but this is something that appends above EaCoN's process, namely in APT (Affymetrix Power Tools). I think you can build your own reference dataset, though this seems to be quite complicated. I probably won't write an official support to handle non-standard (ie, those provided with EaCoN dependencies, initially provided by Affymetrix) reference packages, simply as it would slightly over-complicate the use of EaCoN for only a single feature request yet. If other people ask for it, then I'll go for it.

Cheers
