### ISSUE TITLE
OncoScan.na33.r2 not found

### ISSUE THREAD

**Issue by Aashilbatavia** [gustaveroussy/EaCoN#19]
Hi 
I have previously run this tool and it has worked great, however, recently i received some data back and tried to apply this tool again and recieved the following error:
"Error in apt.oncoscan.process(ATChannelCel = ATChannelCel, GCChannelCel = GCChannelCel,  : 
  Package OncoScan.na33.r2 not found !"

I was trying to find where this error was coming from but am baffled. 

I was hoping you would be able to help

Thanks! 

(i have OncoScanCNV.na33.r2_0.1.0.tar.gz and apt.oncoscan.2.4.0 installed, which work for most of the data i have, i do not have OncoScan.na33.r2 which i guess i need?)

**Comment by l0ka** [comment]
Hi,
I have exactly the same problem as @Aashilbatavia.

Any update?

**Comment by aoumess** [comment]
Thanks @l0ka for the right answer !
Effectively, that's becase Agilent did not give the same name to its annotation release versions for OncoScan and OncoScanCNV releases. It's **r4** for the (older) OncoScan design, and **r2** for the (more recent) OncoScanCNV one.
Cheers
